walmart_sales:
  outputs:
    dev:
      dbname: walmart_db
      host: localhost
      password: root
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: root
  target: dev
walmart_sales_analysis:
  outputs:
    dev:
      dbname: walmart_db
      host: localhost
      pass: root
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: root
  target: dev
